on:
 push:
   tags:
     - '!refs/tags/*'
   branches:
     - '*'

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: update pip
      run: python -m pip install --upgrade pip
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests
      run: coverage run -m pytest -rs
    - name: Tests report
      run: coverage report
    - name: Codecov
      uses: codecov/codecov-action@v1.0.10
